[build]
  publish = "public"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[dev]
  command = "npm run dev"
  port = 8080
  publish = "public"

# Ensure images can be processed without hitting timeout
[build.processing]
  skip_processing = false

[build.processing.images]
  compress = true