[build]
  publish = "public" # Specifies the publish folder
  command = "npm run build" # Specifies the command to build your site

[[plugins]]
  package = "netlify-plugin-image-optim"
  [plugins.inputs]
    # Directories where your images are located
    directories = ["public/assets/images"]
    # Choose other specific options, such as compression type (if needed)
    quality = 80 # Example: setting the quality to 80% for optimized images
