backend:
  name: git-gateway # Git-based backend for Netlify CMS
  branch: main # The branch to update (default is master)

media_folder: "./static/images" # Le chemin local où les images sont stockées pendant l'édition
public_folder: "/images" # Public URL path for images

collections:
  - name: "boats"
    label: "Bateaux"
    editor:
      preview: false
    format: "json"
    extension: "json"
    identifier_field: "model"
    summary: "{{name}}"
    description: "Gérez la liste des bateaux affichés sur le site."
    folder: "_data"  # Dossier où le fichier _data/boats.json est stocké
    create: true
    files:
      - file: "_data/boats.json"  # Spécifie le fichier JSON contenant les bateaux
        label: "Liste des Bateaux"
        name: "boats"
        fields:
  - label: "Bateaux"
    name: "boats"
    widget: "object"
    fields:
      - label: "Liste des bateaux"
        name: "list"
        widget: "list"
        fields:
          - { label: "Modèle", name: "model", widget: "string" }
          - { label: "Nom", name: "name", widget: "string" }
          - { label: "Prix", name: "price", widget: "string" }
          - { label: "Moteur", name: "engine", widget: "string" }
          - { label: "Nombre de passagers", name: "passengersNumber", widget: "string" }
          - { label: "ID du carousel", name: "carousel", widget: "string" }
          - { label: "Texte alternatif de l’image", name: "imageAlt", widget: "string" }



