backend:
  name: git-gateway # Git-based backend for Netlify CMS
  branch: main # The branch to update (default is master)

media_folder: "./static/assets/images/bateaux" # Le chemin local où les images sont stockées pendant l'édition
public_folder: "/assets/images/bateaux" # Public URL path for images

collections:
  - name: "boats"
    label: "Bateaux"
    editor:
      preview: false
    format: "json"
    extension: "json"
    identifier_field: "model"
    summary: "{{name}}"
    description: "Gérez la liste des bateaux affichés sur le site."
    file: "_data/boats.json"
    create: true
    fields:
      - label: "Bateaux"
        name: "boats"
        widget: "list"
        fields:
          - { label: "Modèle", name: "model", widget: "string" }
          - { label: "Nom", name: "name", widget: "string" }
          - { label: "Prix", name: "price", widget: "string" }
          - { label: "Moteur", name: "engine", widget: "string" }
          - { label: "Nombre de passagers", name: "passengersNumber", widget: "string" }
          - { label: "ID du carousel", name: "carousel", widget: "string" }
          - { label: "Texte alternatif de l’image", name: "imageAlt", widget: "string" }

