backend:
  name: git-gateway
  branch: main

media_folder: "static/images" # Stockage local des images uploadées
public_folder: "/images" # URL publique des images

collections:
  - name: "boats"
    label: "Bateaux"
    files:  # To manage a single file rather than multiple entries
      - label: "Bateau Content"  
        name: "bateau"  
        file: "src/_data/boats.json"  # The file where is data
        create: true
        delete: false
        fields: 
          - { label: "Modèle", name: "model", widget: "string" }
          - { label: "Nom", name: "name", widget: "string" }
          - { label: "Prix", name: "price", widget: "string" }
          - { label: "Moteur", name: "engine", widget: "string" }
          - { label: "Nombre de passagers", name: "passengersNumber", widget: "string" }
          - { label: "ID du carousel", name: "carousel", widget: "string" }
          - { label: "Texte alternatif de l’image", name: "imageAlt", widget: "string" }
