backend:
  name: git-gateway
  branch: main

media_folder: "public/assets/images/uploaded"
public_folder: "/assets/images/uploaded"

collections: 
  - name: "bateaux"
    label: "Bateaux"
    folder: "src/collection-boats"
    create: true
    delete: true
    slug: "{{fields.name}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "01-organisms/section-boat.njk" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "boat" }
      - { label: "Nom", name: "name", widget: "hidden", default: "boat_{{uuid}}" }
      - { label: "Modèle", name: "model", widget: "string" }
      - { label: "Prix", name: "price", widget: "string" }
      - { label: "Moteur", name: "engine", widget: "string" }
      - { label: "Nombre de passagers", name: "passengersNumber", widget: "string" }
      - { label: "Carousel", name: "carousel", widget: "hidden", default: "carousel_{{uuid}}" }
      - { label: "Alt de l'image", name: "imageAlt", widget: "string" }
  
  - name: "carousels"
    label: "Images des bateaux"
    folder: "src/collection-carousels"
    create: true
    delete: true
    slug: "{{fields.name}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "01-organisms/carousel.njk" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "carousel" }
      - { label: "Nom", name: "name", widget: "string", pattern: ["^carousel_.*", "Doit commencer par carousel_"] }
      - { label: "Autoplay", name: "autoplay", widget: "hidden", default: true }
      - { label: "Pause on hover", name: "pauseOnHover", widget: "hidden", default: true }
      - label: "Images"
        name: "images"
        widget: "list"
        min: 1
        max: 10
        fields:
          - { label: "ID", name: "name", widget: "hidden", default: "carousel_slide_{{uuid}}" }
          - { label: "Position", name: "objectPosition", widget: "hidden", default: "center" }
  
  # Collection pour éditer uniquement les nouvelles images dans images.json
  - name: "images-file"
    label: "Catalogue d'images"
    files:
      - label: "Ajouter des images"
        name: "images"
        file: "src/_data/atoms/images.json"
        fields:
          - { label: "Style global", name: "globalStyle", widget: "hidden", default: "max-w-full h-auto" }
          - { label: "Variants", name: "variants", widget: "hidden" }
          - { label: "Groups", name: "groups", widget: "hidden" }
          - label: "Images"
            name: "images"
            widget: "list"
            collapsed: false
            minimize_collapsed: true
            summary: "{{fields.name}}: {{fields.alt}}"
            fields:
              - { label: "ID de l'image", name: "name", widget: "string", hint: "Cet ID doit correspondre à celui utilisé dans le carousel" }
              - { label: "Image", name: "src", widget: "image", hint: "Sélectionnez l'image" }
              - { label: "Description", name: "alt", widget: "string", hint: "Description de l'image pour l'accessibilité" }
              - { label: "Groupe", name: "group", widget: "hidden", default: "block-media" }
              - { label: "Taille", name: "size", widget: "hidden", default: "medium" }